### ISSUE TITLE
[Feature Request] Yuito Support

### ISSUE THREAD

**Issue by moriel5** [zacharee/MastodonRedirect#6] opened 2023-07-20 00:57 UTC
Since Yuito is a fork of Subway Tooter, I believe that it should not be too hard to add support for Yuito?

**Comment by zacharee** [comment] 2023-07-20 00:59
Yuito is a fork of Tusky. I can check if the developer has added a share intent.

**Comment by moriel5** [comment] 2023-07-20 01:00
Thanks, I must have mixed up the source.

That would be awesome.

**Comment by moriel5** [comment] 2023-07-20 02:05
Hmm... I guess then that I have another issue to open, in that case.

Thanks for looking into this, I'll try to get the dev behind Yuito to look into this.

**Comment by zacharee** [comment] 2023-09-05 02:58
Closing as a duplicate of #23 for better tracking.

**Closed by zacharee** 2023-09-05 02:58 UTC
Labels: enhancement, no client support
