### ISSUE TITLE
Support Tusky

### ISSUE THREAD

**Issue by tiptoptom** [zacharee/MastodonRedirect#14] opened 2023-08-10 14:58 UTC
Can you add support for Tusky?

**Comment by zacharee** [comment] 2023-08-10 15:09
Tusky doesn't currently have a way to send links to it.

See https://github.com/tuskyapp/Tusky/issues/3865 and #6.

**Comment by zacharee** [comment] 2023-09-05 02:58
Closing as a duplicate of #23 for better tracking.

**Closed by zacharee** 2023-09-05 02:58 UTC
Labels: enhancement, no client support
