### ISSUE TITLE
Support voyager

### ISSUE THREAD

**Issue by kzshantonu** [zacharee/MastodonRedirect#20] opened 2023-09-01 20:16 UTC
https://github.com/aeharding/voyager

PS: love the apps

**Comment by zacharee** [comment] 2023-09-01 20:19
Voyager doesn't have a way to send links to it, unfortunately.

**Comment by zacharee** [comment] 2023-09-05 02:58
Closing as a duplicate of #22 for better tracking.

**Closed by zacharee** 2023-09-05 02:58 UTC
Labels: enhancement, no client support
