### ISSUE TITLE
Support Thunder for Lemmy.

### ISSUE THREAD

**Issue by rozari0** [zacharee/MastodonRedirect#16] opened 2023-08-20 13:03 UTC
Here's the [repo link](https://github.com/thunder-app/thunder).

**Comment by zacharee** [comment] 2023-08-20 13:06
Thunder doesn't have any way to send it links.

**Comment by zacharee** [comment] 2023-09-05 02:58
Closing as a duplicate of #22 for better tracking.

**Closed by zacharee** 2023-09-05 02:58 UTC
Labels: enhancement, no client support
